[package]
name = "cryptotrader-cli"
version = "0.1.0"
authors = ["Rob Saunders <rob@wearebrandnew.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
log = "0.4.5"
simple_logger = "1.0.1"
cryptotrader = { path = "../cryptotrader-core" }
